[options]
addons_path = odoo/addons,custom
admin_passwd = admin
db_host = dpg-d1nm1r3uibrs7387p0j0-a
db_port = 5432
db_user = odoo18_d9gp_user
db_password = ezW7BnzMurNqr3hAWgfGnyXGHyLbM3jB
db_name = odoo18
http_port = 10000
dbfilter = .*
list_db = True
log_level = debug




